# Generated by Django 4.2.27 on 2025-12-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_employee_branch"),
        ("branches", "0001_initial"),
        ("orders", "0003_order_is_paid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="table",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="table",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="branches.branch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("store", "branch", "number")},
        ),
    ]