# Generated by Django 4.2.27 on 2026-01-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]