# Generated by Django 4.2.27 on 2025-12-10 00:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_customers', to='core.store')),
            ],
            options={
                'verbose_name': 'عميل ولاء',
                'verbose_name_plural': 'عملاء الولاء',
                'unique_together': {('store', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EARN', 'إضافة نقاط'), ('REDEEM', 'استبدال نقاط'), ('EXPIRE', 'انتهاء صلاحية')], max_length=10)),
                ('points', models.IntegerField(help_text='موجب = إضافة، سالب = خصم')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.customerloyalty')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='تفعيل نظام الولاء')),
                ('points_per_egp', models.DecimalField(decimal_places=2, default=1.0, help_text='كل كام جنيه يدّي نقطة واحدة (مثلاً: 10.00 = كل 10 جنيه = نقطة)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('egp_per_point', models.DecimalField(decimal_places=2, default=1.0, help_text='كل نقطة تساوي كام جنيه خصم (مثلاً: 1.00 = النقطة بجنيه)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('min_points_to_redeem', models.PositiveIntegerField(default=50, help_text='أقل عدد نقاط للاستبدال')),
                ('expiry_months', models.PositiveIntegerField(blank=True, help_text='عدد الشهور قبل انتهاء النقاط (اتركه فاضي = لا ينتهي)', null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='core.store')),
            ],
            options={
                'verbose_name': 'برنامج الولاء',
                'verbose_name_plural': 'برامج الولاء',
            },
        ),
    ]
