# Generated by Django 4.2.27 on 2025-12-14 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_employee_qr_code_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('QR', 'QR Code'), ('MANUAL', 'Manual'), ('NFC', 'NFC')], default='QR', max_length=10)),
                ('location', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('penalty_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='core.employee')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
    ]
