# Generated by Django 4.2.27 on 2025-12-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0002_employeeshiftassignment_leaverequest_monthlypayroll_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="gps",
            field=models.JSONField(blank=True, null=True),
        ),
    ]