# Generated by Django 4.2.27 on 2025-12-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="qr_menu",
            field=models.ImageField(blank=True, null=True, upload_to="branch_qr/"),
        ),
        migrations.AddField(
            model_name="branch",
            name="qr_menu_base64",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]