# Generated by Django 4.2.27 on 2025-12-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qr_menu',
            field=models.ImageField(blank=True, null=True, upload_to='store_qr/'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_menu_base64',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
