# Generated by Django 4.2.27 on 2025-12-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payrollperiod_employeeledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.store'),
            preserve_default=False,
        ),
    ]
