# Generated by Django 4.2.27 on 2025-12-14 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='qr_code_attendance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qr_code_attendance_base64',
        ),
        migrations.AddField(
            model_name='store',
            name='qr_attendance',
            field=models.ImageField(blank=True, null=True, upload_to='store_qr/'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_attendance_base64',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='attendance_grace_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='سماحية التأخير بالدقائق'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='attendance_penalty_per_15min',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='غرامة كل 15 دقيقة'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='attendance_shift_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='بداية الشفت'),
        ),
    ]
