# Generated by Django 4.2.27 on 2025-12-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_employee_qr_code_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='qr_attendance',
            field=models.ImageField(blank=True, null=True, upload_to='employee_attendance_qr/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qr_attendance_base64',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
