# Generated by Django 4.2.27 on 2025-12-18 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("core", "0006_remove_employee_qr_code_employee_qr_attendance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="branches.branch",
            ),
        ),
    ]