# Generated by Django 4.2.27 on 2025-12-21 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_employee_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeledger",
            name="payout_date",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
    ]