# Generated by Django 4.2.27 on 2025-12-23 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_employeeledger_payout_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollperiod",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="paid_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_payrolls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]