# Generated by Django 4.2.27 on 2025-12-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_payrollperiod_is_paid_payrollperiod_paid_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollperiod",
            name="attendance_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="monthly_salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]