# Generated by Django 4.2.27 on 2025-12-28 01:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_payrollperiod_late_penalties"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_payment_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: seed_trials(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def seed_trials(apps):
    User = apps.get_model("core", "User")

    now = timezone.now()
    trial_end = now + timezone.timedelta(days=14)

    for user in User.objects.filter(
        is_payment_verified=False,
        role__in=["OWNER", "MANAGER"],
    ):
        if not user.trial_starts_at:
            user.trial_starts_at = now
        if not user.trial_ends_at:
            user.trial_ends_at = trial_end
        user.save(update_fields=["trial_starts_at", "trial_ends_at"])