# Generated by Django 4.2.27 on 2025-12-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_user_is_payment_verified_user_trial_ends_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_password_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_password_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]